name: Testing

on:
  pull_request:
    branches:
      - main

jobs:
  spec_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '3.2'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run spec tests
      run: bundle exec rake test
