name: Test

on:
  - pull_request
  - push

env:
  BUNDLE_WITHOUT: release

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "2.7"
          - ruby: "3.2"
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build gem
        run: gem build *.gemspec
      - name: Run tests
        run: bundle exec rspec
